# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sun_rcpp <- function(D, DR, RD, CE, SE) {
    .Call(`_skylight_sun_rcpp`, D, DR, RD, CE, SE)
}

moon_rcpp <- function(D, G, CE, SE, RD, DR) {
    .Call(`_skylight_moon_rcpp`, D, G, CE, SE, RD, DR)
}

altaz_rcpp <- function(DS, H, SD, CI, SI, DR, RD) {
    .Call(`_skylight_altaz_rcpp`, DS, H, SD, CI, SI, DR, RD)
}

refr_rcpp <- function(H, DR) {
    .Call(`_skylight_refr_rcpp`, H, DR)
}

atmos_rcpp <- function(HA, DR) {
    .Call(`_skylight_atmos_rcpp`, HA, DR)
}

