# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' fast C++ implementation of the skylight model
#'
#' Calculates sky illuminance values faster. This function
#' should not be called independently and the formal R
#' skylight() function should be used with the parameter
#' fast = TRUE!
#'
#' @param forcing input matrix with forcing parameters organized
#'  as longitude, latitude, year, month, day, hour, minutes,
#'  sky_conditions
#' @return sky illuminance results as a matrix
skylight_rcpp <- function(forcing) {
    .Call(`_skylight_skylight_rcpp`, forcing)
}

